apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  creationTimestamp: '2018-09-25T09:25:28Z'
  generation: 6
  labels:
    app: mariadb-persistent
    template: mariadb-persistent-template
  name: mariadb
  namespace: readytoinnovate
  resourceVersion: '77725'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/readytoinnovate/deploymentconfigs/mariadb
  uid: f0b0d634-c0a4-11e8-be89-08002771db1a
spec:
  replicas: 1
  selector:
    name: mariadb
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: database_user
                  name: mariadb
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_password
                  name: mariadb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_root_password
                  name: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database_name
                  name: mariadb
          envFrom:
            - secretRef:
                name: mariadb
          image: >-
            registry.access.redhat.com/rhscl/mariadb-102-rhel7@sha256:7d61c9ef8fd1ff8b8a992f5533e073d89b6f4b43f3394f6eb57c509d7b70b728
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mariadb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - mariadb
        from:
          kind: ImageStreamTag
          name: 'mariadb:10.2'
          namespace: openshift
        lastTriggeredImage: >-
          registry.access.redhat.com/rhscl/mariadb-102-rhel7@sha256:7d61c9ef8fd1ff8b8a992f5533e073d89b6f4b43f3394f6eb57c509d7b70b728
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-09-25T09:37:36Z'
      lastUpdateTime: '2018-09-25T09:37:36Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-09-25T09:37:28Z'
      lastUpdateTime: '2018-09-25T09:37:37Z'
      message: replication controller "mariadb-5" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: Manual
    message: manual change
  latestVersion: 5
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
